Add hubspot properties
dlt-hub/verified-sources pull request #206
Opened 2023-07-02 04:13 UTC by steinitzu

- [ ] TODO: missing tests for properties

# Tell us what you do here

- [ ] improving, documenting, customizing existing source (please link an issue or describe below)

# Relevant issue

Implements https://github.com/dlt-hub/verified-sources/issues/195

# More PR info

2023-07-09 14:21 UTC, rudolfix requested changes
looks good! what we still miss:
- show how to fetch history in the demo script
- enable history on the `test_all_reources` (which calls real backend)

2023-07-15 03:53 UTC, steinitzu commented
@rudolfix added it to tests and demo. I don't think I have the right test account locally so I'm not checking the data very thoroughly.

2023-07-15 03:55 UTC, steinitzu commented on sources/hubspot/__init__.py
> +        for history_entries in fetch_property_history(
Changed this too. With some endpoints the URL was too long when listing all properties twice. :fearful:

2023-07-16 11:25 UTC, rudolfix commented
@steinitzu I sent you the credentials to test account. let's make sure that some proper test cases are there before merging. thanks!

2023-07-17 19:01 UTC, rudolfix approved these changes
OK, LTM!

2023-07-17 19:01 UTC, merged