feat: Adding pg_legacy_replication verified source using decoderbufs
dlt-hub/verified-sources pull request #589
Opened 2024-12-23 03:33 UTC by neuromantik33

# Differences between `pg_legacy_replication` and `pg_replication`

## Overview

`pg_legacy_replication` is a fork of the verified `pg_replication` source. The primary goal of this fork is to provide logical replication capabilities for Postgres instances running versions earlier than 10, when the `pgoutput` plugin was not yet available. This fork draws inspiration from the original `pg_replication` source and the `decoderbufs` library, which is actively maintained by Debezium.

## Key Differences from `pg_replication`

### Replication User Ownership Requirements
One of the limitations of native Postgre replication is that the replication user must **own** the tables in order to add them to a **publication**.
Additionally, once a table is added to a publication, it cannot be removed, requiring the creation of a new replication slot, which results in the loss of any state tracking.

### Limitations in `pg_replication`
The current pg_replication implementation has several limitations:
- It supports only a single initial snapshot of the data.
- It requires `CREATE` access to the source database in order to perform the initial snapshot.
- **Superuser** access is required to replicate entire Postgres schemas.
  While the `pg_legacy_replication` source theoretically reads the entire WAL across all schemas, the current implementation using dlt transformers restricts this functionality.
  In practice, this has not been a common use case.
- The implementation is opinionated in its approach to data transfer. Specifically, when updates or deletes are required, it defaults to a `merge` write disposition,
  which replicates live data without tracking changes over time.

### Features of `pg_legacy_replication`

This fork of `pg_replication` addresses the aforementioned limitations and introduces the following improvements:
- Adheres to the dlt philosophy by treating the WAL as an upstream resources. This replication stream is then transformed into various DLT resources, with customizable options for write disposition,
  file formats, type hints, etc., specified at the resource level rather than at the source level.
- Supports an initial snapshot of all tables using the transaction slot isolation level. Additionally, ad-hoc snapshots can be performed using the serializable deferred isolation level,
  similar to `pg_dump`.
- Emphasizes the use of `pyarrow` and parquet formats for efficient data storage and transfer. A dedicated backend has been implemented to support these formats.
- Replication messages are decoded using Protocol Buffers (protobufs) in C, rather than relying on native Python byte buffer parsing. This ensures greater efficiency and performance.

## Next steps
- Add support for the [wal2json](https://github.com/eulerto/wal2json) replication plugin. This is particularly important for environments such as **Amazon RDS**, which supports `wal2json`,
- as opposed to on-premise or Google Cloud SQL instances that support `decoderbufs`.

2025-01-20 20:25 UTC, rudolfix requested changes
this is soo good! thanks for docs and test cases. also pyarrow support is amazing.

I have just a few comments to hacky cleanups you do. but I think nothing really serious.

2025-01-20 20:25 UTC, rudolfix commented on sources/pg_legacy_replication/helpers.py
> +    setattr(engine, "rep_conn", rep_conn)  # noqa
also `sql_table` supports `engine_adapter_callback` now. so you could let `dlt` to create an engine and just provide this function as a callback. in that case each resource will get a separate engine which will be disposed automatically when table is extracted.

2025-01-20 20:25 UTC, rudolfix commented on sources/pg_legacy_replication/helpers.py
> +def cleanup_snapshot_resources(snapshots: DltSource) -> None:
this is used by tests only, right? or is user supposed to do it? if tests only I'd move it to tests.

2025-01-20 20:25 UTC, rudolfix commented on sources/pg_legacy_replication/helpers.py
> +    cur = _get_conn(credentials).cursor()
I think connection implements context manager so maybe:
```pyt
with _get_con() as con:
   cur = con.cursor()
```
is better?

2025-01-20 20:25 UTC, rudolfix commented on sources/pg_legacy_replication/helpers.py
> +    cur.connection.close()
will be called by context manager

2025-01-20 20:25 UTC, rudolfix commented on sources/pg_legacy_replication/helpers.py
> +        cur = _get_conn(credentials).cursor()
again context manager (if possible)

2025-01-20 20:25 UTC, rudolfix commented on sources/pg_legacy_replication/helpers.py
> +            arrow.row_tuples_to_arrow(rows, columns=columns, tz=tz),
so good! could we do the same for regular replication?

2025-01-20 20:25 UTC, rudolfix commented on sources/pg_legacy_replication/README.md
> +in tables (a process often referred to as _Change Data Capture_ or CDC). It uses [logical decoding](https://www.postgresql.org/docs/current/logicaldecoding.html) and the optional `decoderbufs`
what does it mean that `decoderbufs` is optional? if not present, we decode on the client?

2025-01-20 21:00 UTC, rudolfix requested changes
two more things:
1. in the meantime Python 3.8 is EOL and newest poetry does not support it. could you change python 3.,9 in our lint/init CI workflow to 3.9?
2. maybe we can rename this to `pg_wal_replication`? it does not look like legacy to me at all :)

2025-01-20 21:00 UTC, rudolfix commented on sources/pg_legacy_replication/helpers.py
> +@dlt.sources.config.with_config(sections=("sources", "pg_legacy_replication"))
this will not work this way. you need to pass `section="pg_legacy_replication"` into dlt.source or just move this function to __init__.py (which I think is the best option). then both dlt.source share the same configuration

2025-01-22 12:38 UTC, neuromantik33 commented on sources/pg_legacy_replication/__init__.py
> +    handler.__qualname__ = "BackendHandler.__call__"  # type: ignore[attr-defined]
Yes. I have no idea why this is required here is the output with the line commented
```bash
~/repos/github/neuromantik33/verified-sources $ poetry run pytest tests/pg_legacy_replication/test_pg_replication.py::test_core_functionality 
============================= test session starts ==============================
platform linux -- Python 3.11.11, pytest-7.4.2, pluggy-1.3.0 -- /home/drnick/repos/github/neuromantik33/verified-sources/.venv/bin/python
cachedir: .pytest_cache
rootdir: /home/drnick/repos/github/neuromantik33/verified-sources
configfile: pytest.ini
plugins: mock-3.12.0, requests-mock-1.11.0, cov-5.0.0, forked-1.6.0, anyio-4.0.0
collecting ... collected 2 items

tests/pg_legacy_replication/test_pg_replication.py::test_core_functionality[sqlalchemy-duckdb] FAILED [ 50%]
tests/pg_legacy_replication/test_pg_replication.py::test_core_functionality[pyarrow-duckdb] FAILED [100%]

=================================== FAILURES ===================================
__________________ test_core_functionality[sqlalchemy-duckdb] __________________

src_config = (<dlt.pipeline.pipeline.Pipeline object at 0x7f96cf51f3d0>, 'test_slot_a72aac18')
destination_name = 'duckdb', backend = 'sqlalchemy'

    @pytest.mark.parametrize("destination_name", ALL_DESTINATIONS)
    @pytest.mark.parametrize("backend", ["sqlalchemy", "pyarrow"])
    def test_core_functionality(
        src_config: Tuple[dlt.Pipeline, str], destination_name: str, backend: TableBackend
    ) -> None:
        @dlt.resource(write_disposition="merge", primary_key="id_x")
        def tbl_x(data):
            yield data
    
        @dlt.resource(write_disposition="merge", primary_key="id_y")
        def tbl_y(data):
            yield data
    
        src_pl, slot_name = src_config
    
        src_pl.run(
            [
                tbl_x({"id_x": 1, "val_x": "foo"}),
                tbl_y({"id_y": 1, "val_y": True}),
            ]
        )
        add_pk(src_pl.sql_client, "tbl_x", "id_x")
        add_pk(src_pl.sql_client, "tbl_y", "id_y")
    
        snapshots = init_replication(
            slot_name=slot_name,
            schema=src_pl.dataset_name,
            table_names=("tbl_x", "tbl_y"),
            take_snapshots=True,
            table_options={
                "tbl_x": {"backend": backend},
                "tbl_y": {"backend": backend},
            },
        )
    
>       changes = replication_source(
            slot_name=slot_name,
            schema=src_pl.dataset_name,
            table_names=("tbl_x", "tbl_y"),
            repl_options={
                "tbl_x": {"backend": backend},
                "tbl_y": {"backend": backend},
            },
        )

backend    = 'sqlalchemy'
destination_name = 'duckdb'
slot_name  = 'test_slot_a72aac18'
snapshots  = <dlt.extract.source.DltSource object at 0x7f96ceb9fd50>
src_config = (<dlt.pipeline.pipeline.Pipeline object at 0x7f96cf51f3d0>, 'test_slot_a72aac18')
src_pl     = <dlt.pipeline.pipeline.Pipeline object at 0x7f96cf51f3d0>
tbl_x      = <dlt.extract.resource.DltResource object at 0x7f96d8ba9d50>
tbl_y      = <dlt.extract.resource.DltResource object at 0x7f96da95bdd0>

tests/pg_legacy_replication/test_pg_replication.py:65: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.venv/lib/python3.11/site-packages/dlt/extract/decorators.py:195: in __call__
    source = self._deco_f(*args, **kwargs)
        args       = ()
        kwargs     = {'repl_options': {'tbl_x': {'backend': 'sqlalchemy'}, 'tbl_y': {'backend': 'sqlalchemy'}}, 'schema': 'src_pl_dataset_202501221235482995', 'slot_name': 'test_slot_a72aac18', 'table_names': ('tbl_x', 'tbl_y')}
        self       = <dlt.extract.decorators.DltSourceFactoryWrapper object at 0x7f96d7768d90>
.venv/lib/python3.11/site-packages/dlt/extract/decorators.py:280: in _wrap
    return _eval_rv(rv, schema_copy)
        _eval_rv   = <function DltSourceFactoryWrapper._wrap.<locals>._eval_rv at 0x7f96d773fba0>
        _make_schema = <function DltSourceFactoryWrapper._wrap.<locals>._make_schema at 0x7f96cf55c540>
        args       = ()
        conf_f     = <function replication_source at 0x7f96cf55c4a0>
        kwargs     = {'repl_options': {'tbl_x': {'backend': 'sqlalchemy'}, 'tbl_y': {'backend': 'sqlalchemy'}}, 'schema': 'src_pl_dataset_202501221235482995', 'slot_name': 'test_slot_a72aac18', 'table_names': ('tbl_x', 'tbl_y')}
        pipeline_name = 'src_pl'
        proxy      = <dlt.common.pipeline.PipelineContext object at 0x7f96ceb05d10>
        rv         = <generator object replication_source at 0x7f96cd7182c0>
        schema_copy = Schema replication_source at 140285669523216
        source_sections = ('sources', 'pg_legacy_replication', 'replication_source')
.venv/lib/python3.11/site-packages/dlt/extract/decorators.py:240: in _eval_rv
    _rv = list(_rv)
        _rv        = <generator object replication_source at 0x7f96cd7182c0>
        schema_copy = Schema replication_source at 140285669523216
        self       = <dlt.extract.decorators.DltSourceFactoryWrapper object at 0x7f96d7768d90>
        source_section = 'pg_legacy_replication'
sources/pg_legacy_replication/__init__.py:118: in replication_source
    yield dlt.transformer(
        credentials = <dlt.common.configuration.specs.connection_string_credentials.ConnectionStringCredentials object at 0x7f96cd7ffc50>
        flush_slot = True
        repl_options = defaultdict(<function replication_source.<locals>.<lambda> at 0x7f96cd740180>, {'tbl_x': {'backend': 'sqlalchemy'}, 'tbl_y': {'backend': 'sqlalchemy'}})
        replication_resource = <function replication_source.<locals>.replication_resource at 0x7f96cd7ea700>
        schema     = 'src_pl_dataset_202501221235482995'
        slot_name  = 'test_slot_a72aac18'
        table      = 'tbl_x'
        table_names = ('tbl_x', 'tbl_y')
        target_batch_size = 1000
        wal_reader = <dlt.extract.resource.DltResource object at 0x7f96ceba2050>
.venv/lib/python3.11/site-packages/dlt/extract/decorators.py:958: in transformer
    return resource(  # type: ignore
        _impl_cls  = <class 'dlt.extract.resource.DltResource'>
        columns    = None
        data_from  = <dlt.extract.resource.DltResource object at 0x7f96ceba2050>
        f          = BackendHandler(table='tbl_x', repl_options={'backend': 'sqlalchemy'})
        file_format = None
        max_table_nesting = None
        merge_key  = None
        name       = 'tbl_x'
        parallelized = False
        primary_key = None
        schema_contract = None
        selected   = True
        spec       = None
        standalone = False
        table_format = None
        table_name = None
        write_disposition = None
.venv/lib/python3.11/site-packages/dlt/extract/decorators.py:758: in resource
    return decorator(data)
        _impl_cls  = <class 'dlt.extract.resource.DltResource'>
        columns    = None
        data       = BackendHandler(table='tbl_x', repl_options={'backend': 'sqlalchemy'})
        data_from  = <dlt.extract.resource.DltResource object at 0x7f96ceba2050>
        decorator  = <function resource.<locals>.decorator at 0x7f96cd7ea980>
        file_format = None
        make_resource = <function resource.<locals>.make_resource at 0x7f96cd7ea840>
        max_table_nesting = None
        merge_key  = None
        name       = 'tbl_x'
        parallelized = False
        primary_key = None
        references = None
        schema_contract = None
        selected   = True
        spec       = None
        standalone = False
        table_format = None
        table_name = None
        wrap_standalone = <function resource.<locals>.wrap_standalone at 0x7f96cd7ea8e0>
        write_disposition = None
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

f = BackendHandler(table='tbl_x', repl_options={'backend': 'sqlalchemy'})

    def decorator(
        f: Callable[TResourceFunParams, Any]
    ) -> Callable[TResourceFunParams, TDltResourceImpl]:
        i [...]

2025-01-22 13:24 UTC, neuromantik33 commented on sources/pg_legacy_replication/helpers.py
> +    @sa.event.listens_for(engine, "begin")
Fixed

2025-01-22 14:30 UTC, neuromantik33 commented on sources/pg_legacy_replication/helpers.py
> +    setattr(engine, "rep_conn", rep_conn)  # noqa
Well the version of `dlt` provided in the repo is `1.3.0` and the `engine_adapter_callback` wasn't released until 1.4.1. As for keeping the `rep_conn`, I believe the original author also encountered the problem described here https://stackoverflow.com/q/75852587, which is why he needed to save the snapshot into temporary exported tables (which by the way never get dropped), so that the load could be done without the `rep_conn` remaining open.

The problem is that it's impossible to load the snapshot if the rep_conn gets gc and subsequently closed. Commenting out the `setattr` this is what happens:
```python
conn = <sqlalchemy.engine.base.Connection object at 0x7f3ac69a7510>

    @sa.event.listens_for(engine, "begin")
    def on_begin(conn: sa.Connection) -> None:
        cur = conn.connection.cursor()
        if snapshot_name is None:
            # Using the same isolation level that pg_backup uses
            cur.execute(
                "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE, READ ONLY, DEFERRABLE"
            )
        else:
            cur.execute("SET TRANSACTION ISOLATION LEVEL REPEATABLE READ")
>           cur.execute(f"SET TRANSACTION SNAPSHOT '{snapshot_name}'")
E           psycopg2.errors.InvalidParameterValue: invalid snapshot identifier: "00000003-000009FF-1"

conn       = <sqlalchemy.engine.base.Connection object at 0x7f3ac69a7510>
cur        = <cursor object at 0x7f3ac870a2f0; closed: 0>
snapshot_name = '00000003-000009FF-1'
```

2025-01-22 14:32 UTC, neuromantik33 commented on sources/pg_legacy_replication/helpers.py
> +def cleanup_snapshot_resources(snapshots: DltSource) -> None:
Well if you're running dlt in a long lived python executable, it's best to close the engine and drop the `rep_conn` connection. However since I use it in short lived k8s or celery jobs, it's not really necessary. I'm not sure though that it's optional for everyone.

2025-01-22 14:52 UTC, neuromantik33 commented on sources/pg_legacy_replication/helpers.py
> +            arrow.row_tuples_to_arrow(rows, columns=columns, tz=tz),
Of course! I tried my best to do whatever I could to mimic the `sql_database` source capabilities, I don't support `pandas` as backend though. Maybe it that interests someone...

One trick I did which allows me to have a consistent BigQuery partitioning column for `_pg_commit_ts` which is the transaction time, is to add a `item_map` during the initial load on a _normal_ cursor column (ex. `updated_at`) as so
```python
 def add_pg_commit_ts_if_absent(col_name: str) -> ItemTransformFunc[pyarrow.Table]:
    def col_name_to_pg_commit_ts(item: pyarrow.Table) -> pyarrow.Table:
        if "_pg_commit_ts" in item.schema.names:
            return item
        return item.append_column("_pg_commit_ts", item[col_name])

    return col_name_to_pg_commit_ts
```
It's no much more efficient to do this in pyarrow than batches of dicts :sweat_smile:

2025-01-22 14:55 UTC, neuromantik33 commented on sources/pg_legacy_replication/README.md
> +in tables (a process often referred to as _Change Data Capture_ or CDC). It uses [logical decoding](https://www.postgresql.org/docs/current/logicaldecoding.html) and the optional `decoderbufs`
The heavy lifting is done by the decoderbufs extension, which must be added if using a managed postgres like Cloud SQL, or compiled and installed on a self hosted postgres installation.

Detailed instructions can be found here : https://debezium.io/documentation/reference/stable/postgres-plugins.html#logical-decoding-output-plugin-installation

FYI decoderbufs is the default logical replication plugin used by Debezium.

2025-01-22 16:59 UTC, neuromantik33 commented on sources/pg_legacy_replication/helpers.py
> +@dlt.sources.config.with_config(sections=("sources", "pg_legacy_replication"))
I'm not sure about changing the name to `pg_wal_replication`. As you've mentioned, `pgoutput` is now the de-facto way of doing logical replication—being built-in to postgres— and despite its shortcomings most users might now want to add _legacy_ LR plugins. But I really don't care about the name, it's really a means to end for me (getting a replication source to work in pg9.6.

2026-09-15 15:52 UTC, closed without merging