Edamam pipeline
dlt-hub/verified-sources pull request #94
Opened 2023-04-24 09:01 UTC by Anggi-Permana-Harianja

# Tell us what you do here

- [x] contributing new pipeline (please create an issue [here]() and link it below)
- [ ] implementing verified pipeline (please link a relevant issue labelled as `verified pipeline`)
- [ ] fixing a bug (please link a relevant bug report)
- [ ] improving, documenting, customizing existing pipeline (please link relevant issue)
- [ ] anything else (please link an issue or describe below)

# Relevant issue

issue #
[link](https://github.com/dlt-hub/pipelines/issues/95)

# More PR info

2023-04-24 09:18 UTC, Anggi-Permana-Harianja commented
currently, implemented for duckdb

2023-04-25 08:49 UTC, rudolfix requested changes
thx for contribution! see my review

2023-04-25 08:49 UTC, rudolfix commented on pipelines/edamam/__init__.py
> +def edamam_source(api_secrets_key: str = dlt.secrets.value) -> Sequence[DltResource]:
I think for such a simple pipeline you do not even need to declare the source. it is perfectly fine to just use standalone resource as below, but if you declare it, allow to pass the full credentials and also the ingredients. but as said: if you expose the resource as below you just need one.

2023-04-25 08:49 UTC, rudolfix commented on pipelines/edamam/__init__.py
> +@dlt.resource(write_disposition='append')
append probably is OK as default

2023-04-25 08:49 UTC, rudolfix commented on tests/edamam/test_edamam_pipeline.py
> +    assert isinstance(table[0], dict)
the test is good. but you can reuse some building blocks. see tests/utils.py. there's a method that will return you row counts for tables. you also do not need to check the datatypes in the destination. do it by inspecting dlt schema, you already get table here. just check the columns.

2023-05-19 09:38 UTC, rudolfix commented
@Anggi-Permana-Harianja as mentioned we are closing some of the community pipelines PRs. they will be moved to a separate repository or a sharing hub. when this is ready we'll resubmit them

2023-05-19 09:38 UTC, closed without merging